### ISSUE TITLE
 private lateinit var mToast: Toast has a bug，First do FlutterToast.cancel when not init mToast.

### ISSUE THREAD

**Issue by chenguo4930** [ponnamkarthik/FlutterToast#246] opened 2020-11-19 06:30 UTC

**Comment by chenguo4930** [comment] 2020-11-19 06:32
`  "cancel" -> {
                mToast.cancel()
                result.success(true)
            }

need:
  "cancel" -> {
              if(kotlin check init){
                mToast.cancel()
                result.success(true)
              }
            }`

**Comment by ponnamkarthik** [comment] 2020-11-21 00:25
Duplicate of #244

**Closed by ponnamkarthik** 2020-11-21 00:25 UTC
